# Generated by Django 5.2.4 on 2025-07-07 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Rasm')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nashr etilgan sana')),
                ('is_published', models.BooleanField(default=True, verbose_name='Nashr etilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_date'],
            },
        ),
    ]
